name: Notify Slack on merged pull requests

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-apply:
    env:
      working-directory: ./terraform/network
      branch: ${{ github.event.pull_request.base.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: unfor19/install-aws-cli-action@master
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: install vars
        run: chmod +x ./import_vars.sh && ./import_vars.sh test_by_mango ${{ env.branch }}
        working-directory: ${{ env.working-directory }}

      - name: init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: apply
        id: apply
        run: terraform apply -auto-approve -lock=false -var-file=${{ env.branch }}.json
        working-directory: ${{ env.working-directory }}

  notify_merged_pull_request:
    env:
      branch: ${{ github.event.pull_request.base.ref }}
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Tell the action the pr merged outputs
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.branch }} Infrastructure Deploy Success"
                  }
                }
              ],
              "attachments": [
                {
                  "color": "#2EB67D",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Merged Pull Request:* ${{ github.event.pull_request.title }}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Pull Request by :* ${{ github.event.pull_request.user.login }}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "<${{ github.event.pull_request.html_url }}|View Merged Pull Request>"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
