name: terraform-plan

on:
  push:
    paths:
      - 'terraform/network/**'
  pull_request:
    paths: 
      - 'terraform/network/**'

jobs:
  terraform-plan:
    env:
      working-directory: ./terraform/network
    runs-on: ubuntu-latest

    steps:
      - uses: unfor19/install-aws-cli-action@master
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: install vars
        run: chmod +x ./import_vars.sh && ./import_vars.sh --secretName=test_by_mango
        working-directory: ${{ env.working-directory }}

      - name: init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: plan
        run: terraform plan -lock=false -out terraform.plan -var-file=dev.json
        working-directory: ${{ env.working-directory }}

      - name: generate plain output
        run: terraform show -no-color terraform.plan > terraform.text
        working-directory: ${{ env.working-directory }}

      - name: generate json output
        run: terraform show -json terraform.plan > terraform.json
        working-directory: ${{ env.working-directory }}

      - uses: ahmadnassri/action-terraform-report@v3
        with:
          # tell the action the plan outputs
          terraform-text: ${{ github.workspace }}/${{ env.working-directory }}/terraform.text
          terraform-json: ${{ github.workspace }}/${{ env.working-directory }}/terraform.json
          remove-stale-reports: true
